### ISSUE TITLE
Parallelized Radius Query

### ISSUE THREAD

**Issue by clee-ai** [u1234x1234/pynanoflann#6]
Hey! I really like the new multiprocessing capabilities of `kneighbors`, for one of my projects I need to use radius queries, would it be possible to get the same feature for `radius_neighbors`? 

Your library is great, by the way, I have found it to be the fastest option for processing very large point clouds, so thank you!

**Comment by u1234x1234** [comment]
Hi Christopher,

I added multiprocessing to radius searches:
```
pip install git+https://github.com/u1234x1234/pynanoflann.git@0.0.8
```
https://github.com/u1234x1234/pynanoflann/blob/master/tests/test_multithreaded.py#L29

But there's no large speedup (linear) as in the case of kneighbors searches. The reason is the format of returned data. When we do `kneighbors` we know the size of the results: (n_query_points, n_neighbors). But in the case of `radius_neighbors` each query point have an arbitrary (up to index size) number of results. A lot of time is spent on memory allocation / data copying rather than an actual kd-tree computations. It could be made faster if you are fine with the following interface:
list of list of tuples
e.g. for 3 query points:
[[(40, 0.243325), (22, 0.35435345)], [], [(10, 0.3434234)]]
instead of:
[0.243325, 0.35435345], [], [0.3434234]
[40, 22], [], [10]

**Comment by clee-ai** [comment]
Thanks for the help! I'll test the multithreading out in a bit. I ran the non-threaded version and got the following baseline, which is surprisingly speedy:

```
number of query points: 1,048,316
number of tree points: 317,370,183
done building kdtree of radius 15 in 71.807514s
done querying kdtree of radius 15, found 1439777928 results in 323.778020s
```

I'm guessing playing around with `leaf_size` and the multithreading should help performance a bit.

**Comment by clee-ai** [comment]
Hi!

I've found the multithreaded search does reduce query time but significantly increases memory. My usecase is querying with a long array of queries then concatenating the results at the end - I don't care which value came from which query. It may be too specific a use-case for you to support but if it's able to be further memory optimized that would be great! My code is something like this:

```
index = np.random.rand(40_000, 3)
query = np.random.rand(20_000, 3)
		
nn = pynanoflann.KDTree(n_neighbors=5, metric="L2", radius=radius, leaf_size=50)
nn.fit(index)

# query for points
distances_list, indices_list = nn.radius_neighbors(query, n_jobs=cores)

# merge results into one array
dists = np.concatenate(distances_list)
knn_idx = np.concatenate(indices_list)

# do stuff with dists and knn_idx
```

Even for a non-parallel query, I wonder if there's an easy way to reduce memory for these.

**Comment by clee-ai** [comment]
I think what I'll try for now is make a custom c++ function call which aggregates the results from each query point into one list and will prevent having to re-copy data.

**Comment by clee-ai** [comment]
Okay, I ended up writing a more customized wrapper around `radiusSearch`. The multithreading code seems to work great though, so I'll close the issue, thanks!

**Comment by clee-ai** [comment]
Actually, if anyone's interested, I ended up doing this:

https://stackoverflow.com/questions/18086052/find-all-points-within-a-range-to-any-point-of-an-other-set

Basically, I switched the tree and query points, then got the 1-st nearest neighbor using the multithreaded kneighbors. It works for me because I don't care which query point belongs to which tree point, I just want to know the minimum distance from each query point to the tree points. This way avoids having to do multiple radius queries.
